###################################################################################################
# search configuration - the parameters in this section affect results

##################################################
# general
# batches to consider during search
batches: "batches_full.txt"
##################################################

##################################################
# kmer matching

# proportion of kmer presence between the query and the reference for matching, value between 0.00 and 1.00.
# E.g.: if this value is 0.7, then at least 70% of the query kmers must be present in a reference to match it.
# Lower values mean more matches and being able to recover partial hits, but also incurs into more spurious matches.
#     Spurious matches just affect performance and not results - they are filtered out in the alignment phase.
#     E.g. for plasmid search we recommend kmer_thres: 0.33
# Higher values mean less but more accurate matches and faster pipeline execution.
#     E.g. for gene search we recommend kmer_thres: 0.7
kmer_thres: 0.7

# number of best kmer matching hits to keep for each query record (in case of tie, all equivalent hits are included too)
nb_best_hits: 100
##################################################

##################################################
# alignment

# minimap2 preset. Can be:
# map-pb/map-ont: PacBio/Nanopore vs reference mapping
# ava-pb/ava-ont: PacBio/Nanopore read overlap
# asm5/asm10/asm20: asm-to-ref mapping, for ~0.1/1/5% sequence divergence
# splice: long-read spliced alignment
# sr: genomic short-read mapping
minimap_preset: "sr"

# other minimap2 params
minimap_extra_params: "--eqx"
##################################################
###################################################################################################


###################################################################################################
# performance configuration - the parameters in this section does NOT affect results, just performance

##################################################
# general

# overall number of threads to use in the pipeline, an integer number (e.g. 8 for 8 threads) or "all" (to use all threads)
threads: all

# maximum RAM to use in GB - this should be at most 80% of your max RAM
# note: if you use more than your available RAM, constant page swapping will happen and the pipeline will severely
# slow down.
max_ram_gb: 12

# maximum number of heavy I/O jobs. Use this to not overflow the filesystem I/O
max_heavy_io_jobs: 4

# maximum number of download jobs at a time (note: too many might slow down download speed)
max_download_jobs: 8
##################################################

##################################################
# kmer matching
# number of threads when running kmer matching (note: too many might limit the pipeline parallelism)
cobs_thr: 1

# loads the complete kmer index to RAM
# note: this can speed up the pipeline a lot if:
#           1. you have no SSD filesystem, or your filesystem is encrypted or slow for another reason;
#           2. your queries are long (e.g. plasmids) or you have a huge query file;
# We recommend to increase cobs_thr to the max if you set this to True.
# If you get huge slowdowns with this option, the pipeline might be suffering thrashing. Control the RAM usage with the
# max_ram_gb parameter so that you don't get constant page swapping.
load_complete: False
##################################################

##################################################
# alignment
# number of threads when running minimap2 (note: too many might limit the pipeline parallelism)
minimap_threads: 1

# prefer use pipe when running minimap (note: switch this to False only if you are on *Linux* and you have a very fast filesystem)
prefer_pipe: True
##################################################

###################################################################################################


###################################################################################################
# misc configuration

# keep or not decompressed kmer index. If kept, can speed up subsequent searches but will take much more disk
# space, as the decompressed indexes won't be cleaned up.
keep_cobs_ind: False

# directory to store the kmer decompressed indexes. Can be used to put the decompressed indexes in an external
# or large filesystem capable of holding them. If not defined, defaults to "intermediate/00_cobs"
# decompression_dir: cobs_decompressed_indexes

# directory to store all downloaded files. This is where an "asms" folder with all assemblies and a "cobs" folder
# with all COBS indexes will be created. This is a heavy directory, put it in a filesystem that has at least
# 100 GB free
download_dir: "."
###################################################################################################
