###################################################################################################
# search configuration

##################################################
# general
# overall number of threads to use in the pipeline, an integer number (e.g. 8 for 8 threads) or "all" (to use all threads)
thr: all
# batches to consider during search
batches: "batches_full.txt"
# maximum number of xz-decompression jobs at a single time (note: too many might slow down the filesystem)
max_decomp_jobs: 4
# maximum number of download jobs at a time (note: too many might slow down download speed)
max_download_jobs: 8
##################################################

##################################################
# COBS
# number of threads when running COBS (note: too many might limit the pipeline parallelism)
cobs_thr: 1
# COBS threshold in percentage of terms in query matching
cobs_kmer_thres: 0.33
##################################################

##################################################
# minimap2
# minimap preset. Can be: map-pb, map-ont, map-hifi, etc
minimap_preset: "sr"
# number of threads when running mimimap2 (note: too many might limit the pipeline parallelism)
minimap_thr: 1
# other minimap2 params
minimap_extra_params: "--eqx"
##################################################

###################################################################################################


###################################################################################################
# filesystem configuration

# keep or not decompressed COBS index. If kept, can speed up subsequent searches but will take much more disk
# space, as the decompressed indexes won't be cleaned up.
keep_cobs_ind: False

# directory to store the COBS decompressed indexes. Can be used to put the decompressed indexes in an external
# or large filesystem capable of holding them. If not defined, defaults to "intermediate/00_cobs"
# decompression_dir: cobs_decompressed_indexes

# directory to store all downloaded files. This is where an "asms" folder with all assemblies and a "cobs" folder
# with all COBS indexes will be created. This is a heavy directory, put it in a filesystem that has at least
# 100 GB free
download_dir: "."
###################################################################################################


###################################################################################################
# misc configuration

# whether to benchmark or not the pipeline
benchmark: False
###################################################################################################
